### ISSUE TITLE
Link pytest in the introduction with the corresponding training module 

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-cicd#11]
In the introduction, `pytest` is mentioned as recently learned (as part of a training event, likely), but no link or reference is included on where students can learn if that is not the case yet.

**Comment by amanmdesai** [comment]
Hi @michmx I found a link to pytest in the lesson's introduction.  Under the heading as follows:

[Don’t know pytest ?
](https://hsf-training.github.io/hsf-training-cicd/01-introduction/index.html#dont-know-pytest-:~:text=catching%20breaking%20changes.-,Don%E2%80%99t%20know%20pytest%20%3F,-To%20learn%20more)

Shall we also include a link to http://carpentries-incubator.github.io/python-testing/ or some other  link ?
