### ISSUE TITLE
Introduce parallel:matrix jobs like in GitHub Action CI/CD tutorial

### ISSUE THREAD

**Issue by wdconinc** [hsf-training/hsf-training-cicd#34]
The GitHub Actions CI/CD tutorial introduces matrices as a way to replicate similar jobs since it doesn't have `extends` (and since anchors are not all that common for this): https://hsf-training.github.io/hsf-training-cicd-github/09-the-matrix/index.html. 

Gitlab has support for matrices too, https://docs.gitlab.com/ee/ci/yaml/#parallelmatrix (I use them frequently, even though it may not be needed here exactly). It could be useful to present it as an episode, maybe right after https://hsf-training.github.io/hsf-training-cicd/10-the-worlds-a-stage/index.html.

**Comment by GuillermoFidalgo** [comment]
Will add this as a short episode after https://hsf-training.github.io/hsf-training-cicd/07-adding-ci-to-your-code/index.html
