### ISSUE TITLE
Include _authors for author recognition in HTML

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-cicd#46]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

**Comment by GuillermoFidalgo** [comment]
How do we go about this? @klieret

**Comment by GuillermoFidalgo** [comment]
@all-contributors please add @richa2710 for content and please add @GuillermoFidalgo  for content

**Comment by GuillermoFidalgo** [comment]
Let's try this again

@all-contributors please add me for content

**Comment by GuillermoFidalgo** [comment]
@all-contributors please add @GuillermoFidalgo  for content

@all-contributors please add @richa2710 for content

**Comment by GuillermoFidalgo** [comment]
@all-contributors please add @richa2710 for content

**Comment by klieret** [comment]
Hi @GuillermoFidalgo . Sorry, I was behind. Looks like things worked, right?

**Comment by GuillermoFidalgo** [comment]
Yup. All good for now.
